### PR TITLE
Add OpenVPN Server and Client support, Certificate upload and installation

### PR DESCRIPTION
**Pull request by philomory**
I've got a basic implementation of OpenVPN Server and Client creation, as well as uploading and registering certificates and associated keys (as well as other files). This is all working in our environment right now, but I'm sure some of my code could stand to be cleaned up or tweaked.

File and Certificate upload requires the gem 'net-scp' be installed on the device proxy alongside the 'mtik' gem, since the Mikrotik API doesn't really support uploading files.

### CODE REVIEW

**Comment by philomory** [comment]
Is there any interest in having this functionality? If there's any adjustments you'd like made to the pull request in order to be happy merging it, I'd be happy to discuss them.

**Comment by Lavaburn** [comment]
Can you merge this into a single commit (rebased on current master)? I'll gladly merge it if it does not break anything.

**Comment by philomory** [comment]
That's done, hopefully this is structured the way you like.

I have another branch with other new resources and small bugfixes, but unfortunately I wasn't very forward-thinking and did all that work on a single branch so it may take some time for me to un-entangle it into separate pull requests.

**Comment by philomory** [comment]
Sorry, I found a number of additional commits that should have been part of the squashed & rebased pull-request. I think all of the OpenVPN, Certificate and File-related functionality I've implemented is now included in the pull-request.

**Comment by philomory** [comment]
@Lavaburn Does this meet with your approval now?

**Pull request merged**
